feat: add HorizontalMenu ui
Laysi/learn-react-app pull request #9
Opened 2023-07-14 14:35 UTC by Olive020

新增多個button和Dropdown mune 、Switch，以及package兩個模組，用於設計Dropdown mune 、Switch

2023-07-14 20:03 UTC, Ruisi-Lu commented
參考一下我怎麼做 https://github.com/Ruisi-Lu/learn-react-app/commit/12f0f4ec57ab41b83e88bf834501eaae917e8b2c

2023-07-16 00:45 UTC, Ruisi-Lu requested changes
用法錯誤理解

2023-07-16 01:44 UTC, Olive020 commented
> 用法錯誤理解

請問是指&.的部份嗎，應要求已把scss改寫為階層式的，而會使用&.來使用屬性是因為每個button的間距皆不相同無法達成一致而該屬性與HorizontalMenuLink屬同階層，故運用了&.來做為嵌入HorizontalMenuLink的屬性

2023-07-16 02:01 UTC, Ruisi-Lu commented
> > 用法錯誤理解
> 
> 請問是指&.的部份嗎，應要求已把scss改寫為階層式的，而會使用&.來使用屬性是因為每個button的間距皆不相同無法達成一致而該屬性與HorizontalMenuLink屬同階層，故運用了&.來做為嵌入HorizontalMenuLink的屬性

pull the example and read it

2023-07-16 07:45 UTC, Olive020 commented
> > > 用法錯誤理解
> > 
> > 
> > 請問是指&.的部份嗎，應要求已把scss改寫為階層式的，而會使用&.來使用屬性是因為每個button的間距皆不相同無法達成一致而該屬性與HorizontalMenuLink屬同階層，故運用了&.來做為嵌入HorizontalMenuLink的屬性
> 
> pull the example and read it

昨天有全部看過一遍

2023-07-16 08:10 UTC, Olive020 commented
> > > 錯誤理解
> > 
> > 
> > 請問是指&.的其中的嗎，應要求已把scss改寫為階層式的，而會使用&.來使用屬性是因為每個按鈕的佈局格式無法達成一致而該屬性與Horizo​​ntalMenuLink屬同階層，故運用了&.可以為嵌入Horizo​​ntalMenuLink的屬性
> 
> 拉出示例並閱讀它

有再次去修正部份語法

2023-07-16 12:16 UTC, Ruisi-Lu commented
用grammar好像比較不洽當
這個字通常指涉及到文˙法結構，而不是程式語法

2023-07-16 12:18 UTC, Ruisi-Lu commented
約定成俗 css通常使用kebab-case命名 但生成器產生的是upper camel case需要注意一下

2023-07-16 12:34 UTC, Ruisi-Lu requested changes

2023-07-16 12:34 UTC, Ruisi-Lu commented on src/components/HorizontalMenu/HorizontalMenu.scss
> +  top:218px;
你不需要定義元件的位置
這是layout負責的

2023-07-16 12:34 UTC, Ruisi-Lu commented on src/components/HorizontalMenu/HorizontalMenu.scss
> +      }
你不需要為每個按鈕獨立設計寬度 你不覺得你的按鈕歪歪的嗎

2023-07-16 12:34 UTC, Ruisi-Lu commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +const DropdownStyles: StylesConfig = {
為什麼要使用ts來操作css?

2023-07-16 12:34 UTC, Ruisi-Lu commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +  const menuButtons: MenuButton[] = [
你認為為什麼要這樣定義?

2023-07-16 12:34 UTC, Ruisi-Lu commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +        <h5 className="HorizontalMenuLink TestMode"><div className="HorizontalMenuBtn">{'Test Mode'}</div></h5>
為什麼使用h5標籤

2023-07-16 13:10 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.scss
> +  top:218px;
好的，我先刪掉

2023-07-16 13:12 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.scss
> +      }
請問是間距的部份嗎

2023-07-16 14:00 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +const DropdownStyles: StylesConfig = {
有一些屬性並非css有的

2023-07-16 14:04 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +        <h5 className="HorizontalMenuLink TestMode"><div className="HorizontalMenuBtn">{'Test Mode'}</div></h5>
因為Test Mode只是字串

2023-07-16 14:13 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +  const menuButtons: MenuButton[] = [
有link這個屬性，以利<Link>來透過該屬性跳轉到不同button，有知道怎麼用了

2023-07-18 07:39 UTC, LaysDragon commented on src/components/HorizontalMenu/HorizontalMenu.tsx
介面、類別，或者組件都應以大寫命名，代表這是一個"類"

2023-07-18 07:40 UTC, LaysDragon commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +interface horizontalMenuProps { }
介面、類別，或者組件都應以大寫命名，代表這是一個"類"

2023-07-18 07:41 UTC, LaysDragon commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +const DropdownMenu = [
所有變數類，應該以小寫駝峰命名

2023-07-18 08:17 UTC, LaysDragon commented
> 語法

程式語言通常會用Syntax為主

2023-07-18 13:18 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +interface horizontalMenuProps { }
好的，我會再修改的

2023-07-18 13:18 UTC, Olive020 commented on src/components/HorizontalMenu/HorizontalMenu.tsx
> +const DropdownMenu = [
我再去修改

2023-07-18 14:06 UTC, Olive020 commented
主要修改內容:
1.Button間隔統一
2.Dropdown Menu相關屬性放入scss內
3.部分命名格式更改

2023-07-21 03:20 UTC, Olive020 commented
修改內容:
將Dropdown Menu相關屬性放入styles內

2023-07-21 04:45 UTC, Ruisi-Lu commented
我認真看了一下react-select 
我認為它並不適合用在這個場合
我覺得你應該參考這樣的實現方式
https://codepen.io/gitjul/pen/WMNEdr

2023-07-21 06:03 UTC, Olive020 commented
> 我認真看了一下react-select 我認為它並不適合用在這個場合 我覺得你應該參考這樣的實現方式 https://codepen.io/gitjul/pen/WMNEdr
> 
> 補充一下 你的react-select的類型你應該也選錯了 一直有輸入游標在閃

好的，我去參考一下
select的類型沒錯，那個功能用於搜尋清單的，如果不需要那個功能，再把該功能關掉即可

2023-07-22 23:17 UTC, Ruisi-Lu commented
你的commit應該更具體一點
你修改了寬高或是修改了顏色這樣的敘述
你需要讓任何人一眼就知道你在做什麼事情

2023-07-23 09:00 UTC, Olive020 commented
> 你的commit應該更具體一點 你修改了寬高或是修改了顏色這樣的敘述 你需要讓任何人一眼就知道你在做什麼事情

好的，我會再修改的

2023-07-24 06:05 UTC, Ruisi-Lu approved these changes

2023-07-24 06:05 UTC, Ruisi-Lu commented on src/components/HorizontalMenu/HorizontalMenu.scss
> +      }
抱歉沒有拉好
45-63行

2023-07-24 06:06 UTC, merged